//! Golden v14 files generated by FlashMap's public builder. Regeneration is
//! documented in docs/review_probes_2026_09_06.rs and the implementation report.
use rs_lra::{collect_hits, HitCompleteness, MinimizerIndex, SeedIndex};
fn fixture(name: &str) -> MinimizerIndex {
    MinimizerIndex::open(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name),
    )
    .unwrap()
}
#[test]
fn flashmap_capped_singleton_is_not_unique_evidence() {
    let index = fixture("singleton_v14.fmi");
    let seed = index.query_seeds(&[b'A'; 19])[0];
    let (hits, lookup) = collect_hits(&index, &seed);
    assert_eq!(hits.len(), 1);
    assert!(matches!(
        lookup.completeness,
        HitCompleteness::Sampled { stored: 1, .. }
    ));
    assert_eq!(lookup, index.lookup(&seed));
}
#[test]
fn flashmap_compact_key_collision_keeps_each_seeds_own_locus() {
    let index = fixture("collision_v14.fmi");
    for (contig, mut code) in [449396736u64, 943947776].into_iter().enumerate() {
        let mut seq = [0; 19];
        for b in seq.iter_mut().rev() {
            *b = b"ACGT"[(code & 3) as usize];
            code >>= 2;
        }
        let seed = index.query_seeds(&seq)[0];
        let (hits, lookup) = collect_hits(&index, &seed);
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].contig.0, contig as u32);
        assert_eq!(lookup, index.lookup(&seed));
        assert_eq!(lookup.completeness, HitCompleteness::Complete);
    }
}
